-- ================================================================
-- BKAP_COURSES — Schema PostgreSQL
-- ================================================================
-- PostgreSQL không có lệnh USE, và không cho DROP/CREATE DATABASE ngay trong
-- script đang kết nối tới chính database đó. Tạo database từ shell trước:
--
--     createdb -U postgres bkap_courses
--     psql -U postgres -d bkap_courses -f bkap-ai-courses.sql
--
-- Mọi tên bảng/cột đều viết không đặt trong dấu nháy kép, nên PostgreSQL tự hạ
-- về chữ thường. Entity JPA cũng sinh SQL không nháy nên hai bên luôn khớp.
-- ================================================================

-- Xóa theo thứ tự ngược với khóa ngoại
DROP TABLE IF EXISTS Enrollment CASCADE;
DROP TABLE IF EXISTS Course CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ================================================================
-- HÀM TRIGGER: thay thế cho "ON UPDATE NOW()" của MySQL
-- PostgreSQL không hỗ trợ mệnh đề này ở mức cột.
-- ================================================================
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_last_studied_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.last_studied_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ================================================================
-- 1. BẢNG NGƯỜI DÙNG
-- Tên bảng là "users": USER là từ khóa dành riêng của PostgreSQL.
-- ================================================================
CREATE TABLE users (
    id          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname    VARCHAR(100)    NOT NULL,
    email       VARCHAR(150)    NOT NULL UNIQUE,
    username    VARCHAR(50)     NOT NULL UNIQUE,
    phone       VARCHAR(10)     NOT NULL UNIQUE,
    password    VARCHAR(255)    NOT NULL,
    birthday    VARCHAR(12)     NOT NULL,
    role        VARCHAR(20)     NOT NULL DEFAULT 'STUDENT'
                                CHECK (role IN ('STUDENT','ADMIN')),
    createDate  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    last_login  TIMESTAMP       NULL,
    last_logout TIMESTAMP       NULL,
    is_online   BOOLEAN         DEFAULT FALSE
);

-- ================================================================
-- 2. BẢNG DANH MỤC KHÓA HỌC
-- ================================================================
CREATE TABLE Category (
    id          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    slug        VARCHAR(100)    NOT NULL UNIQUE,
    status      VARCHAR(20)     NOT NULL DEFAULT 'active',
    prioty      INTEGER         NOT NULL DEFAULT 0,

    -- Danh mục bên Moodle xếp thành cây. parent_id ghi lại danh mục này nằm
    -- trong danh mục nào; để trống nghĩa là danh mục gốc.
    -- Ví dụ: "Chuyển đổi số cho cơ quan Đảng" nằm trong "Chuyển đổi số".
    parent_id          INTEGER  NULL REFERENCES category(id),

    -- Đối chiếu với danh mục bên Moodle, để lần đồng bộ sau biết bản ghi nào
    -- ứng với danh mục nào thay vì so theo tên.
    moodle_category_id INTEGER  NULL,

    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_category_moodle ON category(moodle_category_id)
    WHERE moodle_category_id IS NOT NULL;

CREATE TRIGGER category_set_updated_at
    BEFORE UPDATE ON Category
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ================================================================
-- 3. BẢNG KHÓA HỌC
-- is_pro dùng SMALLINT chứ không phải BOOLEAN vì entity Course khai kiểu Integer.
-- ================================================================
CREATE TABLE Course (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id         INTEGER         NOT NULL,
    instructor_id       INTEGER         NOT NULL,
    title               VARCHAR(200)    NOT NULL,
    slug                VARCHAR(200)    NOT NULL UNIQUE,
    subtitle            VARCHAR(300),
    description         TEXT,
    thumbnail_url       VARCHAR(500),
    preview_video_url   VARCHAR(500),
    level               VARCHAR(20)     DEFAULT 'ALL'
                                        CHECK (level IN ('BEGINNER','INTERMEDIATE','ADVANCED','ALL')),
    is_pro              SMALLINT        DEFAULT 0,
    price               NUMERIC(12,0)   DEFAULT 0,
    original_price      NUMERIC(12,0)   DEFAULT 0,
    price_type          VARCHAR(20)     DEFAULT 'PAID'
                                        CHECK (price_type IN ('PAID','FREE','CONTACT')),
    rating              NUMERIC(2,1)    DEFAULT 0,
    rating_count        INTEGER         DEFAULT 0,
    student_count       INTEGER         DEFAULT 0,
    lesson_count        INTEGER         DEFAULT 0,
    duration_text       VARCHAR(50),

    -- Khóa học tương ứng bên Moodle. Lưu ID số lấy từ URL /course/view.php?id=...
    -- Cố ý KHÔNG dùng slug đối chiếu idnumber bên Moodle: slug sửa được trong
    -- trang admin, đổi một cái là liên kết đứt âm thầm. ID thì lưu riêng, không
    -- phụ thuộc gì vào slug.
    -- NULL = chưa mở trên LMS, nút "Đăng ký học" sẽ hiện "Sắp khai giảng".
    moodle_course_id    INTEGER,

    -- Khóa đồng bộ từ LMS về mặc định là 'inactive': lúc đó chưa có giá, chưa
    -- phân loại đúng, hiện ngay ra trang chủ thì khách thấy một khóa nham nhở.
    -- Admin điền xong mới chuyển sang 'active'.
    status              VARCHAR(20)     NOT NULL DEFAULT 'active',

    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (category_id)   REFERENCES Category(id),
    FOREIGN KEY (instructor_id) REFERENCES users(id)
);

CREATE TRIGGER course_set_updated_at
    BEFORE UPDATE ON Course
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Mỗi khóa bên Moodle chỉ được nối với đúng một khóa bên buni. Không có ràng
-- buộc này thì hai khóa cùng trỏ vào một khóa LMS, ghi danh sẽ loạn.
-- Dùng chỉ mục có điều kiện vì cột cho phép NULL, mà nhiều khóa chưa nối thì
-- đều NULL — NULL không tính là trùng.
CREATE UNIQUE INDEX idx_course_moodle ON course(moodle_course_id)
    WHERE moodle_course_id IS NOT NULL;

-- ================================================================
-- 4. BẢNG ĐĂNG KÝ KHÓA HỌC & TIẾN ĐỘ
-- ================================================================
CREATE TABLE Enrollment (
    id               INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER      NOT NULL,
    course_id        INTEGER      NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'ENROLLED'
                                  CHECK (status IN ('ENROLLED','IN_PROGRESS','COMPLETED')),
    progress_percent INTEGER      DEFAULT 0,
    enrolled_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    last_studied_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_user_course UNIQUE (user_id, course_id),
    FOREIGN KEY (user_id)   REFERENCES users(id)  ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES Course(id) ON DELETE CASCADE
);

CREATE TRIGGER enrollment_set_last_studied_at
    BEFORE UPDATE ON Enrollment
    FOR EACH ROW EXECUTE FUNCTION set_last_studied_at();

-- ================================================================
-- DATA MẪU: USERS
-- ================================================================
-- Cột password lưu hash BCrypt, không phải mật khẩu thô. Cả 5 hash dưới đây
-- ứng với cùng một mật khẩu mẫu (không ghi ra đây vì file này nằm trên git —
-- hỏi người quản lý dự án). Chúng khác nhau vì BCrypt sinh salt ngẫu nhiên.
--
-- NẠP LÊN MÁY THẬT THÌ ĐỔI MẬT KHẨU NGAY, nhất là tài khoản ADMIN mducpham:
-- mật khẩu mẫu yếu, hash lại công khai trên git nên dò ra được.
--
-- Cần thêm tài khoản thì tạo ở /admin/user hoặc nhập Excel ở /admin/user/import
-- (tự đăng ký đã tắt), để hệ thống tự băm mật khẩu.
INSERT INTO users (fullname, email, username, phone, password, birthday, role) VALUES
('Phạm Minh Đức',  'phamminhduc@gmail.com',  'mducpham', '0901234564', '$2a$10$/lp5acN/I0.7LRzSFZ5DJe9wSdUOlA3ZviLuA44iOWEhqZWSdds02', '1998-12-25', 'ADMIN'),
('Nguyễn Văn An',  'nguyenvanan@gmail.com',  'vanan',    '0901234561', '$2a$10$6Kxcdrh7NpMNOLTcuqqrGeWxBNrCzSYjb9qAOoUxyQKyw5CLXCafS', '2000-05-15', 'STUDENT'),
('Trần Thị Bình',  'tranthibibinh@gmail.com','thibinh',  '0901234562', '$2a$10$kXOKF/bdghBpt/HHfcDaZOIE71roJolGu/qJRyeyqEovV7hEnpuKe', '1999-08-20', 'STUDENT'),
('Lê Hoàng Cường', 'lehoangcuong@gmail.com', 'hcuong',   '0901234563', '$2a$10$.46dW7m5CWxgCAK2F9VOeO11yDOBF0xveWOw6I4ZFXVvPN3fAHAuW', '2001-03-10', 'STUDENT'),
('Hoàng Thị Em',   'hoangthiem@gmail.com',   'thiem',    '0901234565', '$2a$10$qRPMlrj5AdxxG94p09kg3OGWIvCUTYabqzpqlc0miaPWDYToBhZBe', '2002-07-04', 'STUDENT');

-- ================================================================
-- DATA MẪU: CATEGORY (10 bản ghi)
-- ================================================================
INSERT INTO Category (name, slug, status, prioty) VALUES
('Full-Stack Developer', 'full-stack',       'active',   1),
('Frontend Developer',   'frontend',         'active',   2),
('AI & Data Science',    'ai-data-science',  'active',   3),
('Lập trình di động',    'mobile-developer', 'active',   4),
('DevOps & Cloud',       'devops-cloud',     'active',   5),
('Backend Developer',    'backend',          'active',   6),
('Lập trình C/C++',      'c-cpp',            'active',   7),
('Cơ sở dữ liệu',        'database',         'active',   8),
('Bảo mật mạng',         'security',         'inactive', 9),
('UI/UX Design',         'uiux-design',      'active',   10);

-- ================================================================
-- DATA MẪU: COURSE (10 bản ghi)
-- ================================================================
INSERT INTO Course (category_id, instructor_id, title, slug, subtitle, description, thumbnail_url, level, is_pro, price, original_price, price_type, rating, rating_count, student_count, lesson_count, duration_text) VALUES
(1, 2, 'Full-Stack Developer',       'full-stack-developer',    'React • Node.js • MongoDB',  'Thành thạo cả Frontend lẫn Backend.',        'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600', 'ALL',          1, 1399000, 3299000, 'PAID',    4.6, 316, 1240, 498, '389h17p'),
(2, 3, 'Frontend Developer',         'frontend-developer',      'React • Tailwind • Figma',   'Làm chủ giao diện website hiện đại.',        'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600', 'BEGINNER',     0,  299000,  400000, 'PAID',    4.5, 102,  890,  27, '6h18p'),
(2, 4, 'Tailwind CSS',               'tailwind-css-free',       'Build UI nhanh hơn',         'Thiết kế giao diện cực nhanh.',              'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=600', 'BEGINNER',     0,       0,       0, 'FREE',    5.0,   0,   55,   6, '1h53p'),
(2, 3, 'JavaScript Masterclass',     'javascript-masterclass',  'ES6+ • Async • Web API',     'Nền tảng vững chắc về JavaScript.',          'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=600', 'BEGINNER',     0,  199000,  599000, 'PAID',    4.7,  85,  620,  80, '20h30p'),
(3, 1, 'AI & Data Science',          'ai-data-science-pro',     'Python • TensorFlow • ML',   'Xây dựng mô hình học máy và AI.',            'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=600', 'ADVANCED',     1, 1399000, 3299000, 'PAID',    4.8, 612,  540, 296, '55h49p'),
(3, 1, 'Python Data Analysis',       'python-data-analysis',    'Pandas • NumPy • PowerBI',   'Phân tích và trực quan hóa dữ liệu.',        'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600', 'BEGINNER',     0,  599000, 1200000, 'PAID',    4.4,  45,  180,  55, '16h10p'),
(4, 2, 'Mobile Developer',           'mobile-developer-pro',    'React Native • Expo',        'Xây dựng app di động đa nền tảng.',          'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600', 'INTERMEDIATE', 0,  999000, 2500000, 'PAID',    4.3,  87,  498, 120, '25h00p'),
(5, 1, 'DevOps & Cloud AWS',         'devops-cloud-aws',        'Docker • AWS • K8s',         'Làm chủ hạ tầng đám mây và CI/CD.',         'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=600', 'ADVANCED',     1,       0,       0, 'CONTACT', 4.7, 198,  230, 150, '70h15p'),
(5, 5, 'Google Cloud Platform',      'google-cloud-platform',   'GCP • GKE • IAM',            'Kiến trúc hệ thống lớn trên Google Cloud.',  'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600', 'INTERMEDIATE', 0,       0,       0, 'CONTACT', 4.2,  12,   75,  40, '18h00p'),
(1, 4, 'Node.js Backend Developer',  'nodejs-backend-developer','Express • MySQL • JWT',       'Xây dựng RESTful API bảo mật hiệu năng cao.','https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600', 'INTERMEDIATE', 1,  799000, 1890000, 'PAID',    4.6,  92,  340,  95, '35h20p');

-- ================================================================
-- DATA MẪU: ENROLLMENT
-- ================================================================
INSERT INTO Enrollment (user_id, course_id, status, progress_percent) VALUES
(2, 2, 'IN_PROGRESS', 75),
(2, 1, 'COMPLETED',  100);

-- ================================================================
-- KIỂM TRA
-- ================================================================
SELECT * FROM users;
SELECT * FROM Category ORDER BY prioty;
SELECT * FROM Course;
SELECT * FROM Enrollment;

-- Xem cấu trúc bảng (tương đương DESCRIBE của MySQL): gõ \d users trong psql


-- ================================================================
-- 5. BẢNG REFRESH TOKEN
-- ================================================================
-- Access token là JWT, stateless — server không lưu gì nên KHÔNG thu hồi được,
-- lộ ra là dùng được tới khi hết hạn. Vì vậy access token để hạn rất ngắn
-- (15 phút), còn refresh token thì lưu ở đây để có thể thu hồi thật khi người
-- dùng đăng xuất.
--
-- Lưu HASH chứ không lưu token thô: đọc được bảng này mà token còn nguyên dạng
-- thì mạo danh được bất kỳ ai. Cùng lý do với việc băm mật khẩu.
--
-- revoked_at khác NULL nghĩa là token đã bị thu hồi. Giữ lại dòng thay vì xóa
-- để còn lần được dấu vết khi cần điều tra.
CREATE TABLE refresh_token (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER      NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL UNIQUE,
    expires_at  TIMESTAMP    NOT NULL,
    revoked_at  TIMESTAMP    NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_user ON refresh_token(user_id);
