-- ================================================================
-- NÂNG CẤP CSDL ĐANG CHẠY  (KHÔNG phải file dựng mới)
-- ================================================================
-- File bkap-ai-courses.sql chỉ dùng để dựng CSDL từ số không: nó toàn lệnh
-- CREATE TABLE, chạy trên CSDL đã có là lỗi "table already exists" ngay.
--
-- File này làm việc ngược lại: thêm những thứ còn thiếu vào một CSDL đang chạy,
-- không đụng tới dữ liệu sẵn có.
--
-- Cách chạy trên server:
--     psql -U postgres -d bkap_courses -f nang-cap-csdl-server.sql
--
-- Mọi lệnh đều có IF NOT EXISTS nên chạy lại nhiều lần cũng không sao — lần
-- thứ hai trở đi nó chỉ báo "already exists, skipping" rồi đi tiếp.
--
-- LƯU Ý: sao lưu CSDL trước khi chạy.
--     pg_dump -U postgres bkap_courses > sao-luu-truoc-nang-cap.sql
-- ================================================================


-- ----------------------------------------------------------------
-- 1. BẢNG REFRESH TOKEN
-- ----------------------------------------------------------------
-- Bắt buộc phải có trước khi deploy bản mới. Đăng nhập giờ cấp kèm refresh
-- token và ghi vào bảng này — thiếu bảng là ĐĂNG NHẬP HỎNG HOÀN TOÀN, kể cả
-- tài khoản quản trị.
CREATE TABLE IF NOT EXISTS refresh_token (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER      NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL UNIQUE,
    expires_at  TIMESTAMP    NOT NULL,
    revoked_at  TIMESTAMP    NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refresh_token_user ON refresh_token(user_id);


-- ----------------------------------------------------------------
-- 2. NỐI KHÓA HỌC VỚI LMS
-- ----------------------------------------------------------------
-- Lưu ID khóa học bên Moodle, lấy từ URL /course/view.php?id=...
-- Đây là mắt xích để ghi danh và đẩy người học vào đúng khóa.
ALTER TABLE course ADD COLUMN IF NOT EXISTS moodle_course_id INTEGER NULL;

-- Mỗi khóa bên Moodle chỉ được nối với đúng một khóa bên buni.
-- Chỉ mục có điều kiện vì cột cho phép NULL: nhiều khóa chưa nối đều NULL,
-- mà NULL không bị tính là trùng nhau.
CREATE UNIQUE INDEX IF NOT EXISTS idx_course_moodle
    ON course(moodle_course_id) WHERE moodle_course_id IS NOT NULL;


-- ----------------------------------------------------------------
-- 3. TRẠNG THÁI ẨN/HIỆN CHO KHÓA HỌC
-- ----------------------------------------------------------------
-- Khóa đồng bộ từ LMS về nằm ở trạng thái ẩn cho tới khi admin điền giá và
-- phân loại xong. Mặc định 'active' để các khóa đang có không bị biến mất
-- khỏi trang khách sau khi nâng cấp.
ALTER TABLE course ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';


-- ----------------------------------------------------------------
-- 4. CÂY DANH MỤC
-- ----------------------------------------------------------------
-- Moodle xếp danh mục thành cây: "Chuyển đổi số cho cơ quan Đảng" nằm trong
-- "Chuyển đổi số". parent_id giữ lại quan hệ đó; để trống là danh mục gốc.
ALTER TABLE category ADD COLUMN IF NOT EXISTS parent_id INTEGER NULL REFERENCES category(id);

-- Đối chiếu với danh mục bên Moodle, để lần đồng bộ sau biết bản ghi nào ứng
-- với danh mục nào — so theo id chứ không so theo tên.
ALTER TABLE category ADD COLUMN IF NOT EXISTS moodle_category_id INTEGER NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_category_moodle
    ON category(moodle_category_id) WHERE moodle_category_id IS NOT NULL;
    
-- ================================================================
-- KIỂM TRA SAU KHI CHẠY
-- ================================================================
-- Cả 6 dòng dưới đây phải trả về 1. Thiếu dòng nào là lệnh tương ứng chưa chạy.
SELECT 'refresh_token'      AS can_co, count(*) AS ket_qua FROM pg_tables
    WHERE schemaname='public' AND tablename='refresh_token'
UNION ALL SELECT 'course.moodle_course_id',   count(*) FROM information_schema.columns
    WHERE table_name='course'   AND column_name='moodle_course_id'
UNION ALL SELECT 'course.status',             count(*) FROM information_schema.columns
    WHERE table_name='course'   AND column_name='status'
UNION ALL SELECT 'category.parent_id',        count(*) FROM information_schema.columns
    WHERE table_name='category' AND column_name='parent_id'
UNION ALL SELECT 'category.moodle_category_id', count(*) FROM information_schema.columns
    WHERE table_name='category' AND column_name='moodle_category_id'
UNION ALL SELECT 'chi muc idx_course_moodle', count(*) FROM pg_indexes
    WHERE indexname='idx_course_moodle';
